name: Build and publish to npm

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: |
          cargo install wasm-pack

      - name: Build wasm package
        run: |
          wasm-pack build --target nodejs --out-dir pkg

      - name: Remove .gitignore
        run: |
          rm pkg/.gitignore

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Ensure recent npm
        run: npm install -g npm@latest

      - name: Publish to npm
        working-directory: pkg
        run: npm publish --access public
